server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgresql
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5431/postgresql
    locations: filesystem:src/main/resources/db/migration
    enabled: true

