server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/postgresql
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true

  flyway:
      user: postgres
      password: postgres
      url: jdbc:postgresql://localhost:5431/postgresql
      locations: filesystem:src/main/resources/db/migration
      enabled: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            use:
              type:
                headers: false
            value:
              default:
                type: org.openapitools.model.StudentDTO
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual
