openapi: 3.0.0
info:
  title: Group and Student APIs
  description: APIs for managing groups and students
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /groups/create:
    post:
      summary: Create a group
      operationId: createGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupDTO'
      responses:
        '200':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupDTO'
  /groups/allGroups:
    get:
      summary: Get all groups
      operationId: getAllGroups
      responses:
        '200':
          description: Successfully executed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupDTO'
  /groups/groupDetail/{id}:
    get:
      summary: Get group details by ID
      operationId: groupDetail
      parameters:
        - name: id
          in: path
          required: true
          description: Group identifier
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully executed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupDTO'
  /groups/deleteGroup/{id}:
    post:
      summary: Delete group by ID
      operationId: deleteGroup
      parameters:
        - name: id
          in: path
          required: true
          description: Group identifier
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Group successfully deleted
  /groups/updateGroup/{id}:
    put:
      summary: Update group by ID
      operationId: updateGroup
      parameters:
        - name: id
          in: path
          required: true
          description: Group identifier
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupDTO'
      responses:
        '200':
          description: Group successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupDTO'
  /students/students:
    get:
      summary: Get all students
      operationId: getAllStudents
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentDTO'
    post:
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDTO'
      responses:
        '200':
          description: The added student
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDTO'
        '400':
          description: Bad request
  /students/update/{id}:
    put:
      summary: Update a student
      operationId: updateStudent
      parameters:
        - name: id
          in: path
          required: true
          description: Student identifier
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDTO'
      responses:
        '200':
          description: The updated student
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDTO'
        '400':
          description: Bad request
  /students/add:
    post:
      summary: Add a new student
      operationId: addStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDTO'
      responses:
        '200':
          description: The added student
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDTO'
        '400':
          description: Bad request
  /students/delete/{id}:
    post:
      summary: Delete a student by ID
      operationId: deleteStudent
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Student deleted successfully
        '400':
          description: Bad request
  /students/details/{id}:
   get:
      summary: Get student details by ID
      operationId: detailStudent
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Student details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDTO'
        '400':
          description: Bad request
components:
  schemas:
    GroupDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The ID of the group
        groupName:
          type: string
          description: The name of the group
        quantity:
          type: integer
          description: The quantity of students in the group
        studentsList:
          type: array
          items:
            $ref: '#/components/schemas/StudentDTO'
      required:
        - groupName
    StudentDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        studentName:
          type: string
        studentSurname:
          type: string
        phone:
          type: integer
        age:
          type: integer
        groupDTO:
          $ref: '#/components/schemas/GroupDTO'